name: tidal_wave
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  audio_video_progress_bar: ^2.0.2
  just_audio: ^0.9.37
  just_audio_background: ^0.0.1-beta.11
  rxdart: ^0.27.7
  palette_generator: ^0.3.3+3
  flutter_bloc: ^8.1.5
  syncfusion_flutter_sliders: ^25.2.5
  super_tooltip: ^2.0.7
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.4
  dotted_border: ^2.1.0
  file_picker: ^8.0.3
  image_cropper: ^6.0.0
  uuid: ^4.4.0
  firebase_storage: ^11.7.6
  audio_duration: ^0.0.3
  image_picker: ^1.1.1
  path: ^1.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/music/
    - assets/placeholder/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
